site_author: Oleg Yukhnevich
site_name: sweet-spi
site_description: "Simple SPI (Service Provider Interface) for Kotlin Multiplatform (equivalent of JVM's Service Loader)"
site_url: https://whyoleg.github.io/sweet-spi/

repo_name: sweet-spi
repo_url: https://github.com/whyoleg/sweet-spi
remote_branch: gh-pages

copyright: 'Copyright &copy; 2024 Oleg Yukhnevich'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/why_oleg
    - icon: fontawesome/brands/telegram
      link: https://t.me/why_oleg
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/why_oleg
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/whyoleg/

nav:
  - 'Overview': README.md
  - 'Runtime API': runtime-api/index.html
  - 'Gradle Plugin API': gradle-plugin-api/index.html
  - 'Changelog': CHANGELOG.md

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'deep purple'
      accent: 'white'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'deep purple'
      accent: 'white'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy

markdown_extensions:
  - smarty
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - toc:
      permalink: true

plugins:
  - search
